### ISSUE TITLE
Would you please add git tag in the repository?

### ISSUE THREAD

**Issue by dannyxx001** [BafS/mu#1]
Hello, I'm an intern from [cdnjs](https://github.com/cdnjs/cdnjs). I want to add your library, however, we need to use git tag as version control and auto update when you update something in the future. So would you please add git tag in the repository? Thank you. :)
cc [cdnjs/#7717](https://github.com/cdnjs/cdnjs/issues/7717)

**Comment by BafS** [comment]
Hi,
Thank you for the feedback ! I have created a tag (https://github.com/BafS/mu/releases/tag/v0.2.0), I will continue to do that for the next versions. Tanks to you !

**Comment by dannyxx001** [comment]
Thanks for your collaboration. :)
